// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Loops.OpenApiClient.V1.ApiKey;
using Soenneker.Loops.OpenApiClient.V1.AudienceSegments;
using Soenneker.Loops.OpenApiClient.V1.CampaignGroups;
using Soenneker.Loops.OpenApiClient.V1.Campaigns;
using Soenneker.Loops.OpenApiClient.V1.Components;
using Soenneker.Loops.OpenApiClient.V1.Contacts;
using Soenneker.Loops.OpenApiClient.V1.DedicatedSendingIps;
using Soenneker.Loops.OpenApiClient.V1.EmailMessages;
using Soenneker.Loops.OpenApiClient.V1.Events;
using Soenneker.Loops.OpenApiClient.V1.Lists;
using Soenneker.Loops.OpenApiClient.V1.Themes;
using Soenneker.Loops.OpenApiClient.V1.Transactional;
using Soenneker.Loops.OpenApiClient.V1.TransactionalEmails;
using Soenneker.Loops.OpenApiClient.V1.TransactionalGroups;
using Soenneker.Loops.OpenApiClient.V1.Uploads;
using Soenneker.Loops.OpenApiClient.V1.Workflows;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Loops.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apiKey property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.ApiKey.ApiKeyRequestBuilder ApiKey
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.ApiKey.ApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The audienceSegments property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.AudienceSegments.AudienceSegmentsRequestBuilder AudienceSegments
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.AudienceSegments.AudienceSegmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The campaignGroups property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.CampaignGroups.CampaignGroupsRequestBuilder CampaignGroups
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.CampaignGroups.CampaignGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The campaigns property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Campaigns.CampaignsRequestBuilder Campaigns
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Campaigns.CampaignsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The components property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Components.ComponentsRequestBuilder Components
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Components.ComponentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dedicatedSendingIps property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.DedicatedSendingIps.DedicatedSendingIpsRequestBuilder DedicatedSendingIps
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.DedicatedSendingIps.DedicatedSendingIpsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emailMessages property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.EmailMessages.EmailMessagesRequestBuilder EmailMessages
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.EmailMessages.EmailMessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Lists.ListsRequestBuilder Lists
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The themes property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Themes.ThemesRequestBuilder Themes
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Themes.ThemesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactional property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Transactional.TransactionalRequestBuilder Transactional
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Transactional.TransactionalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactionalEmails property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.TransactionalEmails.TransactionalEmailsRequestBuilder TransactionalEmails
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.TransactionalEmails.TransactionalEmailsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactionalGroups property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.TransactionalGroups.TransactionalGroupsRequestBuilder TransactionalGroups
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.TransactionalGroups.TransactionalGroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploads property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Uploads.UploadsRequestBuilder Uploads
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Uploads.UploadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
