// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActivityConditionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "activity")]
        #pragma warning disable CS1591
        Activity,
        #pragma warning restore CS1591
    }
}
