// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BlankTriggerWorkflowMutationNodeTypeName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BlankTrigger")]
        #pragma warning disable CS1591
        BlankTrigger,
        #pragma warning restore CS1591
    }
}
