// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CampaignSchedulingMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "now")]
        #pragma warning disable CS1591
        Now,
        #pragma warning restore CS1591
        [EnumMember(Value = "schedule")]
        #pragma warning disable CS1591
        Schedule,
        #pragma warning restore CS1591
    }
}
