// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListPreview"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListUpdatedResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChangeWorkflowMailingListResponse : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListPreview"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListPreview? WorkflowMailingListPreview { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListPreview WorkflowMailingListPreview { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListUpdatedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListUpdatedResponse? WorkflowMailingListUpdatedResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListUpdatedResponse WorkflowMailingListUpdatedResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.ChangeWorkflowMailingListResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.ChangeWorkflowMailingListResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Loops.OpenApiClient.Models.ChangeWorkflowMailingListResponse();
            if("WorkflowMailingListPreview".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkflowMailingListPreview = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListPreview();
            }
            else if("WorkflowMailingListUpdatedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkflowMailingListUpdatedResponse = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListUpdatedResponse();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(WorkflowMailingListPreview != null)
            {
                return WorkflowMailingListPreview.GetFieldDeserializers();
            }
            else if(WorkflowMailingListUpdatedResponse != null)
            {
                return WorkflowMailingListUpdatedResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(WorkflowMailingListPreview != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListPreview>(null, WorkflowMailingListPreview);
            }
            else if(WorkflowMailingListUpdatedResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowMailingListUpdatedResponse>(null, WorkflowMailingListUpdatedResponse);
            }
        }
    }
}
#pragma warning restore CS0618
