// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChangeWorkflowMailingListRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>If `true`, the request will be validated but the workflow will not be modified.</summary>
        public bool? DryRun { get; set; }
        /// <summary>The workflow revision token returned by the latest workflow read or mutation. Older workflows may return `null` before their first revision-aware mutation; pass `null` back as `expectedRevisionId` in that case. If the token is stale, the API returns a `409 Conflict` error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpectedRevisionId { get; set; }
#nullable restore
#else
        public string ExpectedRevisionId { get; set; }
#endif
        /// <summary>&quot;The mailing list to use for the workflow. When assigning a mailing list, queued contacts excluded by the new list can return `queuedContactsFound`; retry with `queuedContactPolicy: \&quot;discard\&quot;` to apply the change and discard those contacts. Use `null` to clear the workflow mailing list; clearing does not discard queued contacts.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailingListId { get; set; }
#nullable restore
#else
        public string MailingListId { get; set; }
#endif
        /// <summary>`fail` returns queued-contact impact instead of mutating. `discard` confirms that matching queued contacts should be discarded. Defaults to `fail` when omitted.</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowQueuedContactPolicy? QueuedContactPolicy { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.ChangeWorkflowMailingListRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.ChangeWorkflowMailingListRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.ChangeWorkflowMailingListRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dryRun", n => { DryRun = n.GetBoolValue(); } },
                { "expectedRevisionId", n => { ExpectedRevisionId = n.GetStringValue(); } },
                { "mailingListId", n => { MailingListId = n.GetStringValue(); } },
                { "queuedContactPolicy", n => { QueuedContactPolicy = n.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowQueuedContactPolicy>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("dryRun", DryRun);
            writer.WriteStringValue("expectedRevisionId", ExpectedRevisionId);
            writer.WriteStringValue("mailingListId", MailingListId);
            writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowQueuedContactPolicy>("queuedContactPolicy", QueuedContactPolicy);
        }
    }
}
#pragma warning restore CS0618
