// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContactPropertyTriggerWorkflowNodeTypeName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ContactPropertyTrigger")]
        #pragma warning disable CS1591
        ContactPropertyTrigger,
        #pragma warning restore CS1591
    }
}
