// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCampaignResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A tree of audience conditions combined with `match`. Null when the campaign targets a mailing list or segment without an explicit filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter? AudienceFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter AudienceFilter { get; set; }
#endif
        /// <summary>The ID of the audience segment this campaign targets, if set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudienceSegmentId { get; set; }
#nullable restore
#else
        public string AudienceSegmentId { get; set; }
#endif
        /// <summary>The ID of the campaign group this campaign belongs to, if set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignGroupId { get; set; }
#nullable restore
#else
        public string CampaignGroupId { get; set; }
#endif
        /// <summary>ISO 8601 timestamp for when the campaign was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The `contentRevisionId` of the newly created email message. Pass this as `expectedRevisionId` on your first update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailMessageContentRevisionId { get; set; }
#nullable restore
#else
        public string EmailMessageContentRevisionId { get; set; }
#endif
        /// <summary>The ID of the empty email message created for this campaign. Use `POST /v1/email-messages/{emailMessageId}` to set its fields and LMX content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailMessageId { get; set; }
#nullable restore
#else
        public string EmailMessageId { get; set; }
#endif
        /// <summary>The ID of the campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ID of the mailing list this campaign sends to, if set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailingListId { get; set; }
#nullable restore
#else
        public string MailingListId { get; set; }
#endif
        /// <summary>The name of the campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When the campaign is scheduled to send.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.CampaignScheduling? Scheduling { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.CampaignScheduling Scheduling { get; set; }
#endif
        /// <summary>The status of the campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>ISO 8601 timestamp for when the campaign was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateCampaignResponse"/> and sets the default values.
        /// </summary>
        public CreateCampaignResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateCampaignResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.CreateCampaignResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.CreateCampaignResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audienceFilter", n => { AudienceFilter = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter>(global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter.CreateFromDiscriminatorValue); } },
                { "audienceSegmentId", n => { AudienceSegmentId = n.GetStringValue(); } },
                { "campaignGroupId", n => { CampaignGroupId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "emailMessageContentRevisionId", n => { EmailMessageContentRevisionId = n.GetStringValue(); } },
                { "emailMessageId", n => { EmailMessageId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mailingListId", n => { MailingListId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "scheduling", n => { Scheduling = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.CampaignScheduling>(global::Soenneker.Loops.OpenApiClient.Models.CampaignScheduling.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter>("audienceFilter", AudienceFilter);
            writer.WriteStringValue("audienceSegmentId", AudienceSegmentId);
            writer.WriteStringValue("campaignGroupId", CampaignGroupId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("emailMessageContentRevisionId", EmailMessageContentRevisionId);
            writer.WriteStringValue("emailMessageId", EmailMessageId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("mailingListId", MailingListId);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.CampaignScheduling>("scheduling", Scheduling);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
