// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>Node types that can be created with the API. `*Trigger` nodes and `ExitAction` nodes cannot be created.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateWorkflowNodeTypeName
    {
        [EnumMember(Value = "AudienceFilter")]
        #pragma warning disable CS1591
        AudienceFilter,
        #pragma warning restore CS1591
        [EnumMember(Value = "BranchNode")]
        #pragma warning disable CS1591
        BranchNode,
        #pragma warning restore CS1591
        [EnumMember(Value = "ExperimentBranchNode")]
        #pragma warning disable CS1591
        ExperimentBranchNode,
        #pragma warning restore CS1591
        [EnumMember(Value = "TimerAction")]
        #pragma warning disable CS1591
        TimerAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "SendEmailAction")]
        #pragma warning disable CS1591
        SendEmailAction,
        #pragma warning restore CS1591
        [EnumMember(Value = "VariantNode")]
        #pragma warning disable CS1591
        VariantNode,
        #pragma warning restore CS1591
    }
}
