// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>The status of the campaign (always `Draft` for new campaigns).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateCampaignResponseStatus
    {
        [EnumMember(Value = "Draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
    }
}
