// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBeforeRequest"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBetweenRequest"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateWorkflowNodeRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBeforeRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBeforeRequest? CreateWorkflowNodeBeforeRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBeforeRequest CreateWorkflowNodeBeforeRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBetweenRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBetweenRequest? CreateWorkflowNodeBetweenRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBetweenRequest CreateWorkflowNodeBetweenRequest { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("insertMode")?.GetStringValue();
            var result = new global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeRequest();
            if("before".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateWorkflowNodeBeforeRequest = new global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBeforeRequest();
            }
            else if("between".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CreateWorkflowNodeBetweenRequest = new global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBetweenRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateWorkflowNodeBeforeRequest != null)
            {
                return CreateWorkflowNodeBeforeRequest.GetFieldDeserializers();
            }
            else if(CreateWorkflowNodeBetweenRequest != null)
            {
                return CreateWorkflowNodeBetweenRequest.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateWorkflowNodeBeforeRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBeforeRequest>(null, CreateWorkflowNodeBeforeRequest);
            }
            else if(CreateWorkflowNodeBetweenRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.CreateWorkflowNodeBetweenRequest>(null, CreateWorkflowNodeBetweenRequest);
            }
        }
    }
}
#pragma warning restore CS0618
