// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EmailMessageResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The email BCC address. Only present when set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BccEmail { get; set; }
#nullable restore
#else
        public string BccEmail { get; set; }
#endif
        /// <summary>The campaign this email message belongs to. Present only when the message belongs to a campaign (mutually exclusive with `transactionalId`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CampaignId { get; set; }
#nullable restore
#else
        public string CampaignId { get; set; }
#endif
        /// <summary>The email CC address. Only present when set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CcEmail { get; set; }
#nullable restore
#else
        public string CcEmail { get; set; }
#endif
        /// <summary>Fallback values for contact properties. Only present when set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseContactPropertiesFallbacksProperty? ContactPropertiesFallbacks { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseContactPropertiesFallbacksProperty ContactPropertiesFallbacks { get; set; }
#endif
        /// <summary>The current content revision. Pass this as `expectedRevisionId` on your next update.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentRevisionId { get; set; }
#nullable restore
#else
        public string ContentRevisionId { get; set; }
#endif
        /// <summary>Fallback values for data variables. Only present when set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseDataVariablesFallbacksProperty? DataVariablesFallbacks { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseDataVariablesFallbacksProperty DataVariablesFallbacks { get; set; }
#endif
        /// <summary>The rendering format of the email.</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEmailFormat? EmailFormat { get; set; }
        /// <summary>Fallback values for event properties. Only present when set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEventPropertiesFallbacksProperty? EventPropertiesFallbacks { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEventPropertiesFallbacksProperty EventPropertiesFallbacks { get; set; }
#endif
        /// <summary>The email sender email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromEmail { get; set; }
#nullable restore
#else
        public string FromEmail { get; set; }
#endif
        /// <summary>The email sender name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromName { get; set; }
#nullable restore
#else
        public string FromName { get; set; }
#endif
        /// <summary>The ID of the email message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Only present when set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LanguageCode { get; set; }
#nullable restore
#else
        public string LanguageCode { get; set; }
#endif
        /// <summary>The email body serialized as LMX.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lmx { get; set; }
#nullable restore
#else
        public string Lmx { get; set; }
#endif
        /// <summary>The email preview text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewText { get; set; }
#nullable restore
#else
        public string PreviewText { get; set; }
#endif
        /// <summary>The email reply-to address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyToEmail { get; set; }
#nullable restore
#else
        public string ReplyToEmail { get; set; }
#endif
        /// <summary>The email subject.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The transactional email this email message belongs to. Present only when the message belongs to a transactional email (mutually exclusive with `campaignId`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionalId { get; set; }
#nullable restore
#else
        public string TransactionalId { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Non-fatal issues raised while compiling the submitted LMX. Only present on update responses when warnings were produced.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseWarningsItem>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseWarningsItem> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponse"/> and sets the default values.
        /// </summary>
        public EmailMessageResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bccEmail", n => { BccEmail = n.GetStringValue(); } },
                { "campaignId", n => { CampaignId = n.GetStringValue(); } },
                { "ccEmail", n => { CcEmail = n.GetStringValue(); } },
                { "contactPropertiesFallbacks", n => { ContactPropertiesFallbacks = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseContactPropertiesFallbacksProperty>(global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseContactPropertiesFallbacksProperty.CreateFromDiscriminatorValue); } },
                { "contentRevisionId", n => { ContentRevisionId = n.GetStringValue(); } },
                { "dataVariablesFallbacks", n => { DataVariablesFallbacks = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseDataVariablesFallbacksProperty>(global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseDataVariablesFallbacksProperty.CreateFromDiscriminatorValue); } },
                { "emailFormat", n => { EmailFormat = n.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEmailFormat>(); } },
                { "eventPropertiesFallbacks", n => { EventPropertiesFallbacks = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEventPropertiesFallbacksProperty>(global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEventPropertiesFallbacksProperty.CreateFromDiscriminatorValue); } },
                { "fromEmail", n => { FromEmail = n.GetStringValue(); } },
                { "fromName", n => { FromName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "languageCode", n => { LanguageCode = n.GetStringValue(); } },
                { "lmx", n => { Lmx = n.GetStringValue(); } },
                { "previewText", n => { PreviewText = n.GetStringValue(); } },
                { "replyToEmail", n => { ReplyToEmail = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "transactionalId", n => { TransactionalId = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseWarningsItem>(global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseWarningsItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bccEmail", BccEmail);
            writer.WriteStringValue("campaignId", CampaignId);
            writer.WriteStringValue("ccEmail", CcEmail);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseContactPropertiesFallbacksProperty>("contactPropertiesFallbacks", ContactPropertiesFallbacks);
            writer.WriteStringValue("contentRevisionId", ContentRevisionId);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseDataVariablesFallbacksProperty>("dataVariablesFallbacks", DataVariablesFallbacks);
            writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEmailFormat>("emailFormat", EmailFormat);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseEventPropertiesFallbacksProperty>("eventPropertiesFallbacks", EventPropertiesFallbacks);
            writer.WriteStringValue("fromEmail", FromEmail);
            writer.WriteStringValue("fromName", FromName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("languageCode", LanguageCode);
            writer.WriteStringValue("lmx", Lmx);
            writer.WriteStringValue("previewText", PreviewText);
            writer.WriteStringValue("replyToEmail", ReplyToEmail);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("transactionalId", TransactionalId);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.EmailMessageResponseWarningsItem>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
