// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>The platform that sent this event pattern, if the event pattern is from an incoming webhook. Will be `null` for custom events.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventPatternIncomingWebhookPlatform
    {
        [EnumMember(Value = "clerk")]
        #pragma warning disable CS1591
        Clerk,
        #pragma warning restore CS1591
        [EnumMember(Value = "polar")]
        #pragma warning disable CS1591
        Polar,
        #pragma warning restore CS1591
        [EnumMember(Value = "stripe")]
        #pragma warning disable CS1591
        Stripe,
        #pragma warning restore CS1591
        [EnumMember(Value = "supabase")]
        #pragma warning disable CS1591
        Supabase,
        #pragma warning restore CS1591
        [EnumMember(Value = "null")]
        #pragma warning disable CS1591
        NullValue,
        #pragma warning restore CS1591
    }
}
