// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>The identifier of the Guardian rule that fired.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GuardianRuleRule
    {
        [EnumMember(Value = "unsupportedContactProperties")]
        #pragma warning disable CS1591
        UnsupportedContactProperties,
        #pragma warning restore CS1591
        [EnumMember(Value = "missingFallbackContactProperties")]
        #pragma warning disable CS1591
        MissingFallbackContactProperties,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupportedEventProperties")]
        #pragma warning disable CS1591
        UnsupportedEventProperties,
        #pragma warning restore CS1591
        [EnumMember(Value = "missingFallbackEventProperties")]
        #pragma warning disable CS1591
        MissingFallbackEventProperties,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsupportedDataVariables")]
        #pragma warning disable CS1591
        UnsupportedDataVariables,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidCustomDataVariables")]
        #pragma warning disable CS1591
        InvalidCustomDataVariables,
        #pragma warning restore CS1591
        [EnumMember(Value = "missingRequiredDataVariables")]
        #pragma warning disable CS1591
        MissingRequiredDataVariables,
        #pragma warning restore CS1591
        [EnumMember(Value = "missingButtonHrefs")]
        #pragma warning disable CS1591
        MissingButtonHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidButtonHrefs")]
        #pragma warning disable CS1591
        InvalidButtonHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "shortenedYouTubeButtonHrefs")]
        #pragma warning disable CS1591
        ShortenedYouTubeButtonHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "missingLinkHrefs")]
        #pragma warning disable CS1591
        MissingLinkHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalidLinkHrefs")]
        #pragma warning disable CS1591
        InvalidLinkHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "shortenedYouTubeLinkHrefs")]
        #pragma warning disable CS1591
        ShortenedYouTubeLinkHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "shortenedYouTubeImageHrefs")]
        #pragma warning disable CS1591
        ShortenedYouTubeImageHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "emailWithoutMailtoButtonHrefs")]
        #pragma warning disable CS1591
        EmailWithoutMailtoButtonHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "emailWithoutMailtoLinkHrefs")]
        #pragma warning disable CS1591
        EmailWithoutMailtoLinkHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "emailWithoutMailtoImageHrefs")]
        #pragma warning disable CS1591
        EmailWithoutMailtoImageHrefs,
        #pragma warning restore CS1591
        [EnumMember(Value = "bareArrayNodes")]
        #pragma warning disable CS1591
        BareArrayNodes,
        #pragma warning restore CS1591
        [EnumMember(Value = "missingSocialIconHrefs")]
        #pragma warning disable CS1591
        MissingSocialIconHrefs,
        #pragma warning restore CS1591
    }
}
