// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PropertyConditionOperator
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
        [EnumMember(Value = "contains")]
        #pragma warning disable CS1591
        Contains,
        #pragma warning restore CS1591
        [EnumMember(Value = "notContains")]
        #pragma warning disable CS1591
        NotContains,
        #pragma warning restore CS1591
        [EnumMember(Value = "equals")]
        #pragma warning disable CS1591
        Equals,
        #pragma warning restore CS1591
        [EnumMember(Value = "notEquals")]
        #pragma warning disable CS1591
        NotEquals,
        #pragma warning restore CS1591
        [EnumMember(Value = "greaterThan")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "lessThan")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "isTrue")]
        #pragma warning disable CS1591
        IsTrue,
        #pragma warning restore CS1591
        [EnumMember(Value = "isFalse")]
        #pragma warning disable CS1591
        IsFalse,
        #pragma warning restore CS1591
        [EnumMember(Value = "empty")]
        #pragma warning disable CS1591
        Empty,
        #pragma warning restore CS1591
        [EnumMember(Value = "notEmpty")]
        #pragma warning disable CS1591
        NotEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "dateEmpty")]
        #pragma warning disable CS1591
        DateEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "dateNotEmpty")]
        #pragma warning disable CS1591
        DateNotEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "after")]
        #pragma warning disable CS1591
        After,
        #pragma warning restore CS1591
        [EnumMember(Value = "before")]
        #pragma warning disable CS1591
        Before,
        #pragma warning restore CS1591
        [EnumMember(Value = "between")]
        #pragma warning disable CS1591
        Between,
        #pragma warning restore CS1591
    }
}
