// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Flat map of style attributes, matching the attribute names accepted by the LMX `&lt;Style /&gt;` tag. Only keys with a value set on the theme are returned; all keys are optional.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThemeStyles : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The backgroundColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackgroundColor { get; set; }
#nullable restore
#else
        public string BackgroundColor { get; set; }
#endif
        /// <summary>The backgroundXPadding property</summary>
        public double? BackgroundXPadding { get; set; }
        /// <summary>The backgroundYPadding property</summary>
        public double? BackgroundYPadding { get; set; }
        /// <summary>The bodyColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyColor { get; set; }
#nullable restore
#else
        public string BodyColor { get; set; }
#endif
        /// <summary>The bodyFontCategory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyFontCategory { get; set; }
#nullable restore
#else
        public string BodyFontCategory { get; set; }
#endif
        /// <summary>The bodyFontFamily property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyFontFamily { get; set; }
#nullable restore
#else
        public string BodyFontFamily { get; set; }
#endif
        /// <summary>The bodyXPadding property</summary>
        public double? BodyXPadding { get; set; }
        /// <summary>The bodyYPadding property</summary>
        public double? BodyYPadding { get; set; }
        /// <summary>The borderColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BorderColor { get; set; }
#nullable restore
#else
        public string BorderColor { get; set; }
#endif
        /// <summary>The borderRadius property</summary>
        public double? BorderRadius { get; set; }
        /// <summary>The borderWidth property</summary>
        public double? BorderWidth { get; set; }
        /// <summary>The buttonBodyColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ButtonBodyColor { get; set; }
#nullable restore
#else
        public string ButtonBodyColor { get; set; }
#endif
        /// <summary>The buttonBodyXPadding property</summary>
        public double? ButtonBodyXPadding { get; set; }
        /// <summary>The buttonBodyYPadding property</summary>
        public double? ButtonBodyYPadding { get; set; }
        /// <summary>The buttonBorderColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ButtonBorderColor { get; set; }
#nullable restore
#else
        public string ButtonBorderColor { get; set; }
#endif
        /// <summary>The buttonBorderRadius property</summary>
        public double? ButtonBorderRadius { get; set; }
        /// <summary>The buttonBorderWidth property</summary>
        public double? ButtonBorderWidth { get; set; }
        /// <summary>The buttonTextColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ButtonTextColor { get; set; }
#nullable restore
#else
        public string ButtonTextColor { get; set; }
#endif
        /// <summary>The buttonTextFontSize property</summary>
        public double? ButtonTextFontSize { get; set; }
        /// <summary>The buttonTextFormat property</summary>
        public double? ButtonTextFormat { get; set; }
        /// <summary>The dividerBorderWidth property</summary>
        public double? DividerBorderWidth { get; set; }
        /// <summary>The dividerColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DividerColor { get; set; }
#nullable restore
#else
        public string DividerColor { get; set; }
#endif
        /// <summary>The heading1Color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Heading1Color { get; set; }
#nullable restore
#else
        public string Heading1Color { get; set; }
#endif
        /// <summary>The heading1FontSize property</summary>
        public double? Heading1FontSize { get; set; }
        /// <summary>The heading1LetterSpacing property</summary>
        public double? Heading1LetterSpacing { get; set; }
        /// <summary>The heading1LineHeight property</summary>
        public double? Heading1LineHeight { get; set; }
        /// <summary>The heading2Color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Heading2Color { get; set; }
#nullable restore
#else
        public string Heading2Color { get; set; }
#endif
        /// <summary>The heading2FontSize property</summary>
        public double? Heading2FontSize { get; set; }
        /// <summary>The heading2LetterSpacing property</summary>
        public double? Heading2LetterSpacing { get; set; }
        /// <summary>The heading2LineHeight property</summary>
        public double? Heading2LineHeight { get; set; }
        /// <summary>The heading3Color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Heading3Color { get; set; }
#nullable restore
#else
        public string Heading3Color { get; set; }
#endif
        /// <summary>The heading3FontSize property</summary>
        public double? Heading3FontSize { get; set; }
        /// <summary>The heading3LetterSpacing property</summary>
        public double? Heading3LetterSpacing { get; set; }
        /// <summary>The heading3LineHeight property</summary>
        public double? Heading3LineHeight { get; set; }
        /// <summary>The textBaseColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextBaseColor { get; set; }
#nullable restore
#else
        public string TextBaseColor { get; set; }
#endif
        /// <summary>The textBaseFontSize property</summary>
        public double? TextBaseFontSize { get; set; }
        /// <summary>The textBaseLetterSpacing property</summary>
        public double? TextBaseLetterSpacing { get; set; }
        /// <summary>The textBaseLineHeight property</summary>
        public double? TextBaseLineHeight { get; set; }
        /// <summary>The textLinkColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextLinkColor { get; set; }
#nullable restore
#else
        public string TextLinkColor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.ThemeStyles"/> and sets the default values.
        /// </summary>
        public ThemeStyles()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.ThemeStyles"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.ThemeStyles CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.ThemeStyles();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backgroundColor", n => { BackgroundColor = n.GetStringValue(); } },
                { "backgroundXPadding", n => { BackgroundXPadding = n.GetDoubleValue(); } },
                { "backgroundYPadding", n => { BackgroundYPadding = n.GetDoubleValue(); } },
                { "bodyColor", n => { BodyColor = n.GetStringValue(); } },
                { "bodyFontCategory", n => { BodyFontCategory = n.GetStringValue(); } },
                { "bodyFontFamily", n => { BodyFontFamily = n.GetStringValue(); } },
                { "bodyXPadding", n => { BodyXPadding = n.GetDoubleValue(); } },
                { "bodyYPadding", n => { BodyYPadding = n.GetDoubleValue(); } },
                { "borderColor", n => { BorderColor = n.GetStringValue(); } },
                { "borderRadius", n => { BorderRadius = n.GetDoubleValue(); } },
                { "borderWidth", n => { BorderWidth = n.GetDoubleValue(); } },
                { "buttonBodyColor", n => { ButtonBodyColor = n.GetStringValue(); } },
                { "buttonBodyXPadding", n => { ButtonBodyXPadding = n.GetDoubleValue(); } },
                { "buttonBodyYPadding", n => { ButtonBodyYPadding = n.GetDoubleValue(); } },
                { "buttonBorderColor", n => { ButtonBorderColor = n.GetStringValue(); } },
                { "buttonBorderRadius", n => { ButtonBorderRadius = n.GetDoubleValue(); } },
                { "buttonBorderWidth", n => { ButtonBorderWidth = n.GetDoubleValue(); } },
                { "buttonTextColor", n => { ButtonTextColor = n.GetStringValue(); } },
                { "buttonTextFontSize", n => { ButtonTextFontSize = n.GetDoubleValue(); } },
                { "buttonTextFormat", n => { ButtonTextFormat = n.GetDoubleValue(); } },
                { "dividerBorderWidth", n => { DividerBorderWidth = n.GetDoubleValue(); } },
                { "dividerColor", n => { DividerColor = n.GetStringValue(); } },
                { "heading1Color", n => { Heading1Color = n.GetStringValue(); } },
                { "heading1FontSize", n => { Heading1FontSize = n.GetDoubleValue(); } },
                { "heading1LetterSpacing", n => { Heading1LetterSpacing = n.GetDoubleValue(); } },
                { "heading1LineHeight", n => { Heading1LineHeight = n.GetDoubleValue(); } },
                { "heading2Color", n => { Heading2Color = n.GetStringValue(); } },
                { "heading2FontSize", n => { Heading2FontSize = n.GetDoubleValue(); } },
                { "heading2LetterSpacing", n => { Heading2LetterSpacing = n.GetDoubleValue(); } },
                { "heading2LineHeight", n => { Heading2LineHeight = n.GetDoubleValue(); } },
                { "heading3Color", n => { Heading3Color = n.GetStringValue(); } },
                { "heading3FontSize", n => { Heading3FontSize = n.GetDoubleValue(); } },
                { "heading3LetterSpacing", n => { Heading3LetterSpacing = n.GetDoubleValue(); } },
                { "heading3LineHeight", n => { Heading3LineHeight = n.GetDoubleValue(); } },
                { "textBaseColor", n => { TextBaseColor = n.GetStringValue(); } },
                { "textBaseFontSize", n => { TextBaseFontSize = n.GetDoubleValue(); } },
                { "textBaseLetterSpacing", n => { TextBaseLetterSpacing = n.GetDoubleValue(); } },
                { "textBaseLineHeight", n => { TextBaseLineHeight = n.GetDoubleValue(); } },
                { "textLinkColor", n => { TextLinkColor = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("backgroundColor", BackgroundColor);
            writer.WriteDoubleValue("backgroundXPadding", BackgroundXPadding);
            writer.WriteDoubleValue("backgroundYPadding", BackgroundYPadding);
            writer.WriteStringValue("bodyColor", BodyColor);
            writer.WriteStringValue("bodyFontCategory", BodyFontCategory);
            writer.WriteStringValue("bodyFontFamily", BodyFontFamily);
            writer.WriteDoubleValue("bodyXPadding", BodyXPadding);
            writer.WriteDoubleValue("bodyYPadding", BodyYPadding);
            writer.WriteStringValue("borderColor", BorderColor);
            writer.WriteDoubleValue("borderRadius", BorderRadius);
            writer.WriteDoubleValue("borderWidth", BorderWidth);
            writer.WriteStringValue("buttonBodyColor", ButtonBodyColor);
            writer.WriteDoubleValue("buttonBodyXPadding", ButtonBodyXPadding);
            writer.WriteDoubleValue("buttonBodyYPadding", ButtonBodyYPadding);
            writer.WriteStringValue("buttonBorderColor", ButtonBorderColor);
            writer.WriteDoubleValue("buttonBorderRadius", ButtonBorderRadius);
            writer.WriteDoubleValue("buttonBorderWidth", ButtonBorderWidth);
            writer.WriteStringValue("buttonTextColor", ButtonTextColor);
            writer.WriteDoubleValue("buttonTextFontSize", ButtonTextFontSize);
            writer.WriteDoubleValue("buttonTextFormat", ButtonTextFormat);
            writer.WriteDoubleValue("dividerBorderWidth", DividerBorderWidth);
            writer.WriteStringValue("dividerColor", DividerColor);
            writer.WriteStringValue("heading1Color", Heading1Color);
            writer.WriteDoubleValue("heading1FontSize", Heading1FontSize);
            writer.WriteDoubleValue("heading1LetterSpacing", Heading1LetterSpacing);
            writer.WriteDoubleValue("heading1LineHeight", Heading1LineHeight);
            writer.WriteStringValue("heading2Color", Heading2Color);
            writer.WriteDoubleValue("heading2FontSize", Heading2FontSize);
            writer.WriteDoubleValue("heading2LetterSpacing", Heading2LetterSpacing);
            writer.WriteDoubleValue("heading2LineHeight", Heading2LineHeight);
            writer.WriteStringValue("heading3Color", Heading3Color);
            writer.WriteDoubleValue("heading3FontSize", Heading3FontSize);
            writer.WriteDoubleValue("heading3LetterSpacing", Heading3LetterSpacing);
            writer.WriteDoubleValue("heading3LineHeight", Heading3LineHeight);
            writer.WriteStringValue("textBaseColor", TextBaseColor);
            writer.WriteDoubleValue("textBaseFontSize", TextBaseFontSize);
            writer.WriteDoubleValue("textBaseLetterSpacing", TextBaseLetterSpacing);
            writer.WriteDoubleValue("textBaseLineHeight", TextBaseLineHeight);
            writer.WriteStringValue("textLinkColor", TextLinkColor);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
