// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>The rendering format of the email.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateEmailMessageRequestEmailFormat
    {
        [EnumMember(Value = "styled")]
        #pragma warning disable CS1591
        Styled,
        #pragma warning restore CS1591
        [EnumMember(Value = "plain")]
        #pragma warning disable CS1591
        Plain,
        #pragma warning restore CS1591
    }
}
