// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateEmailMessageRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>BCC email address. Requires the team to have CC/BCC enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BccEmail { get; set; }
#nullable restore
#else
        public string BccEmail { get; set; }
#endif
        /// <summary>CC email address. Requires the team to have CC/BCC enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CcEmail { get; set; }
#nullable restore
#else
        public string CcEmail { get; set; }
#endif
        /// <summary>&quot;Fallback values for contact properties, keyed by property name. Per-key merge: a string value sets the fallback, a null value deletes it, and keys omitted from the map are left unchanged.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestContactPropertiesFallbacksProperty? ContactPropertiesFallbacks { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestContactPropertiesFallbacksProperty ContactPropertiesFallbacks { get; set; }
#endif
        /// <summary>&quot;Fallback values for data variables, keyed by variable name. Per-key merge: a string value sets the fallback, a null value deletes it, and keys omitted from the map are left unchanged.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestDataVariablesFallbacksProperty? DataVariablesFallbacks { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestDataVariablesFallbacksProperty DataVariablesFallbacks { get; set; }
#endif
        /// <summary>The rendering format of the email.</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEmailFormat? EmailFormat { get; set; }
        /// <summary>&quot;Fallback values for event properties, keyed by property name. Per-key merge: a string value sets the fallback, a null value deletes it, and keys omitted from the map are left unchanged.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEventPropertiesFallbacksProperty? EventPropertiesFallbacks { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEventPropertiesFallbacksProperty EventPropertiesFallbacks { get; set; }
#endif
        /// <summary>The `contentRevisionId` you last fetched, or the `emailMessageContentRevisionId` you received when creating the campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpectedRevisionId { get; set; }
#nullable restore
#else
        public string ExpectedRevisionId { get; set; }
#endif
        /// <summary>The email sender email address, without the team&apos;s sending domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromEmail { get; set; }
#nullable restore
#else
        public string FromEmail { get; set; }
#endif
        /// <summary>The fromName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromName { get; set; }
#nullable restore
#else
        public string FromName { get; set; }
#endif
        /// <summary>Language code for the email. Requires translation to be enabled for the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LanguageCode { get; set; }
#nullable restore
#else
        public string LanguageCode { get; set; }
#endif
        /// <summary>The email body serialized as LMX. Styles must be embedded in the LMX `&lt;Style /&gt;` tag.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lmx { get; set; }
#nullable restore
#else
        public string Lmx { get; set; }
#endif
        /// <summary>The previewText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewText { get; set; }
#nullable restore
#else
        public string PreviewText { get; set; }
#endif
        /// <summary>Reply-to email. Must be empty or a valid email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyToEmail { get; set; }
#nullable restore
#else
        public string ReplyToEmail { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bccEmail", n => { BccEmail = n.GetStringValue(); } },
                { "ccEmail", n => { CcEmail = n.GetStringValue(); } },
                { "contactPropertiesFallbacks", n => { ContactPropertiesFallbacks = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestContactPropertiesFallbacksProperty>(global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestContactPropertiesFallbacksProperty.CreateFromDiscriminatorValue); } },
                { "dataVariablesFallbacks", n => { DataVariablesFallbacks = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestDataVariablesFallbacksProperty>(global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestDataVariablesFallbacksProperty.CreateFromDiscriminatorValue); } },
                { "emailFormat", n => { EmailFormat = n.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEmailFormat>(); } },
                { "eventPropertiesFallbacks", n => { EventPropertiesFallbacks = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEventPropertiesFallbacksProperty>(global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEventPropertiesFallbacksProperty.CreateFromDiscriminatorValue); } },
                { "expectedRevisionId", n => { ExpectedRevisionId = n.GetStringValue(); } },
                { "fromEmail", n => { FromEmail = n.GetStringValue(); } },
                { "fromName", n => { FromName = n.GetStringValue(); } },
                { "languageCode", n => { LanguageCode = n.GetStringValue(); } },
                { "lmx", n => { Lmx = n.GetStringValue(); } },
                { "previewText", n => { PreviewText = n.GetStringValue(); } },
                { "replyToEmail", n => { ReplyToEmail = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bccEmail", BccEmail);
            writer.WriteStringValue("ccEmail", CcEmail);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestContactPropertiesFallbacksProperty>("contactPropertiesFallbacks", ContactPropertiesFallbacks);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestDataVariablesFallbacksProperty>("dataVariablesFallbacks", DataVariablesFallbacks);
            writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEmailFormat>("emailFormat", EmailFormat);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.UpdateEmailMessageRequestEventPropertiesFallbacksProperty>("eventPropertiesFallbacks", EventPropertiesFallbacks);
            writer.WriteStringValue("expectedRevisionId", ExpectedRevisionId);
            writer.WriteStringValue("fromEmail", FromEmail);
            writer.WriteStringValue("fromName", FromName);
            writer.WriteStringValue("languageCode", LanguageCode);
            writer.WriteStringValue("lmx", Lmx);
            writer.WriteStringValue("previewText", PreviewText);
            writer.WriteStringValue("replyToEmail", ReplyToEmail);
            writer.WriteStringValue("subject", Subject);
        }
    }
}
#pragma warning restore CS0618
