// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowAddToListTriggerPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowAudienceFilterPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventTriggerPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowExperimentBranchPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowSignupTriggerPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerActionPayload"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowVariantPayload"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateWorkflowNodePayload : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowAddToListTriggerPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowAddToListTriggerPayload? WorkflowAddToListTriggerPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowAddToListTriggerPayload WorkflowAddToListTriggerPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowAudienceFilterPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowAudienceFilterPayload? WorkflowAudienceFilterPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowAudienceFilterPayload WorkflowAudienceFilterPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload? WorkflowContactPropertyTriggerPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload WorkflowContactPropertyTriggerPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventTriggerPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventTriggerPayload? WorkflowEventTriggerPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventTriggerPayload WorkflowEventTriggerPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowExperimentBranchPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowExperimentBranchPayload? WorkflowExperimentBranchPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowExperimentBranchPayload WorkflowExperimentBranchPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowSignupTriggerPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowSignupTriggerPayload? WorkflowSignupTriggerPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowSignupTriggerPayload WorkflowSignupTriggerPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerActionPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerActionPayload? WorkflowTimerActionPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerActionPayload WorkflowTimerActionPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowVariantPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowVariantPayload? WorkflowVariantPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowVariantPayload WorkflowVariantPayload { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodePayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodePayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodePayload();
            result.WorkflowAddToListTriggerPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowAddToListTriggerPayload();
            result.WorkflowAudienceFilterPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowAudienceFilterPayload();
            result.WorkflowContactPropertyTriggerPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload();
            result.WorkflowEventTriggerPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventTriggerPayload();
            result.WorkflowExperimentBranchPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowExperimentBranchPayload();
            result.WorkflowSignupTriggerPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowSignupTriggerPayload();
            result.WorkflowTimerActionPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerActionPayload();
            result.WorkflowVariantPayload = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowVariantPayload();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(WorkflowAddToListTriggerPayload != null || WorkflowAudienceFilterPayload != null || WorkflowContactPropertyTriggerPayload != null || WorkflowEventTriggerPayload != null || WorkflowExperimentBranchPayload != null || WorkflowSignupTriggerPayload != null || WorkflowTimerActionPayload != null || WorkflowVariantPayload != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WorkflowAddToListTriggerPayload, WorkflowAudienceFilterPayload, WorkflowContactPropertyTriggerPayload, WorkflowEventTriggerPayload, WorkflowExperimentBranchPayload, WorkflowSignupTriggerPayload, WorkflowTimerActionPayload, WorkflowVariantPayload);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowAddToListTriggerPayload>(null, WorkflowAddToListTriggerPayload, WorkflowAudienceFilterPayload, WorkflowContactPropertyTriggerPayload, WorkflowEventTriggerPayload, WorkflowExperimentBranchPayload, WorkflowSignupTriggerPayload, WorkflowTimerActionPayload, WorkflowVariantPayload);
        }
    }
}
#pragma warning restore CS0618
