// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>The type of email this event relates to. Workflow emails use `loop`. Not available for transactional emails.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebhookMarketingEmailMetricPayloadSourceType
    {
        [EnumMember(Value = "loop")]
        #pragma warning disable CS1591
        Loop,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign")]
        #pragma warning disable CS1591
        Campaign,
        #pragma warning restore CS1591
    }
}
