// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhookLoopEmailSentPayload : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contactIdentity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WebhookContactIdentity? ContactIdentity { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WebhookContactIdentity ContactIdentity { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WebhookEmail? Email { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WebhookEmail Email { get; set; }
#endif
        /// <summary>The eventName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventName { get; set; }
#nullable restore
#else
        public string EventName { get; set; }
#endif
        /// <summary>Unix timestamp in seconds.</summary>
        public int? EventTime { get; set; }
        /// <summary>The ID of the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoopId { get; set; }
#nullable restore
#else
        public string LoopId { get; set; }
#endif
        /// <summary>The name of the workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoopName { get; set; }
#nullable restore
#else
        public string LoopName { get; set; }
#endif
        /// <summary>The mailing list(s) the email was sent to, or an empty array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Loops.OpenApiClient.Models.WebhookMailingList>? MailingLists { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Loops.OpenApiClient.Models.WebhookMailingList> MailingLists { get; set; }
#endif
        /// <summary>The webhookSchemaVersion property</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.Value100WebhookSchemaVersion? WebhookSchemaVersion { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.WebhookLoopEmailSentPayload"/> and sets the default values.
        /// </summary>
        public WebhookLoopEmailSentPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.WebhookLoopEmailSentPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.WebhookLoopEmailSentPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.WebhookLoopEmailSentPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contactIdentity", n => { ContactIdentity = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WebhookContactIdentity>(global::Soenneker.Loops.OpenApiClient.Models.WebhookContactIdentity.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WebhookEmail>(global::Soenneker.Loops.OpenApiClient.Models.WebhookEmail.CreateFromDiscriminatorValue); } },
                { "eventName", n => { EventName = n.GetStringValue(); } },
                { "eventTime", n => { EventTime = n.GetIntValue(); } },
                { "loopId", n => { LoopId = n.GetStringValue(); } },
                { "loopName", n => { LoopName = n.GetStringValue(); } },
                { "mailingLists", n => { MailingLists = n.GetCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.WebhookMailingList>(global::Soenneker.Loops.OpenApiClient.Models.WebhookMailingList.CreateFromDiscriminatorValue)?.AsList(); } },
                { "webhookSchemaVersion", n => { WebhookSchemaVersion = n.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.Value100WebhookSchemaVersion>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WebhookContactIdentity>("contactIdentity", ContactIdentity);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WebhookEmail>("email", Email);
            writer.WriteStringValue("eventName", EventName);
            writer.WriteIntValue("eventTime", EventTime);
            writer.WriteStringValue("loopId", LoopId);
            writer.WriteStringValue("loopName", LoopName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.WebhookMailingList>("mailingLists", MailingLists);
            writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.Value100WebhookSchemaVersion>("webhookSchemaVersion", WebhookSchemaVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
