// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowContactPropertyComparisonOperator
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
        [EnumMember(Value = "contains")]
        #pragma warning disable CS1591
        Contains,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_contains")]
        #pragma warning disable CS1591
        NotContains,
        #pragma warning restore CS1591
        [EnumMember(Value = "empty")]
        #pragma warning disable CS1591
        Empty,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_empty")]
        #pragma warning disable CS1591
        NotEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "equal")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_equal")]
        #pragma warning disable CS1591
        NotEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "greater_than")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "less_than")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "false")]
        #pragma warning disable CS1591
        FalseValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "numeric_equal")]
        #pragma warning disable CS1591
        NumericEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "numeric_not_equal")]
        #pragma warning disable CS1591
        NumericNotEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_empty")]
        #pragma warning disable CS1591
        DateEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "date_not_empty")]
        #pragma warning disable CS1591
        DateNotEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "after")]
        #pragma warning disable CS1591
        After,
        #pragma warning restore CS1591
        [EnumMember(Value = "before")]
        #pragma warning disable CS1591
        Before,
        #pragma warning restore CS1591
        [EnumMember(Value = "between")]
        #pragma warning disable CS1591
        Between,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign")]
        #pragma warning disable CS1591
        Campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "any_loop_email")]
        #pragma warning disable CS1591
        AnyLoopEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "specific_loop_email")]
        #pragma warning disable CS1591
        SpecificLoopEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "accepted_opt_in")]
        #pragma warning disable CS1591
        AcceptedOptIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected_opt_in")]
        #pragma warning disable CS1591
        RejectedOptIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_opt_in")]
        #pragma warning disable CS1591
        PendingOptIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_opt_in")]
        #pragma warning disable CS1591
        NotOptIn,
        #pragma warning restore CS1591
    }
}
