// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Detailed workflow node returned from a mutation, plus the latest workflow revision token.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowMutationNodeWithRevision : IAdditionalDataHolder, IComposedTypeWrapper, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowMutationNodeWithRevision? AddToListTriggerWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowMutationNodeWithRevision AddToListTriggerWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The amount of time to wait before triggering the next node. Set to `0` to move to the next node immediately.</summary>
        public double? Amount { get; set; }
        /// <summary>If `true`, the audience filter will apply to all downstream nodes. If `false`, the audience filter will only apply to the current node. Matches the &quot;Filter scope&quot; option in the UI.</summary>
        public bool? AppliesDownstream { get; set; }
        /// <summary>A tree of audience conditions combined with `match`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter? AudienceFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter AudienceFilter { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowMutationNodeWithRevision? AudienceFilterWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowMutationNodeWithRevision AudienceFilterWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The ID of the audience segment this trigger targets.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudienceSegmentId { get; set; }
#nullable restore
#else
        public string AudienceSegmentId { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowMutationNodeWithRevision? BlankTriggerWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowMutationNodeWithRevision BlankTriggerWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowMutationNodeWithRevision? BranchWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowMutationNodeWithRevision BranchWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The contactPropertyQuery property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeContactPropertyQuery? ContactPropertyQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeContactPropertyQuery ContactPropertyQuery { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeWithRevision? ContactPropertyTriggerWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeWithRevision ContactPropertyTriggerWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The ID of the email message to send. To edit this email, use the `POST /v1/email-messages/{emailMessageId}` endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailMessageId { get; set; }
#nullable restore
#else
        public string EmailMessageId { get; set; }
#endif
        /// <summary>The name of the event pattern that triggers this node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventName { get; set; }
#nullable restore
#else
        public string EventName { get; set; }
#endif
        /// <summary>The properties of the event pattern, which can be used in emails.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty>? EventProperties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty> EventProperties { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowMutationNodeWithRevision? EventTriggerWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowMutationNodeWithRevision EventTriggerWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowMutationNodeWithRevision? ExitActionWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowMutationNodeWithRevision ExitActionWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowMutationNodeWithRevision? ExperimentBranchWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowMutationNodeWithRevision ExperimentBranchWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this is the control variant of an experiment.</summary>
        public bool? IsControl { get; set; }
        /// <summary>The ID of the mailing list this trigger sends to, if set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailingListId { get; set; }
#nullable restore
#else
        public string MailingListId { get; set; }
#endif
        /// <summary>The IDs of the nodes that are downstream of this node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NextNodeIds { get; set; }
#nullable restore
#else
        public List<string> NextNodeIds { get; set; }
#endif
        /// <summary>If `true`, the contacts will be able to enter this workflow every time the trigger is matched. If `false`, contacts will only ever enter this workflow once. Matches the &quot;Trigger frequency&quot; option in the UI.</summary>
        public bool? ReEligible { get; set; }
        /// <summary>The percentage of contacts that will be sent to variant branches, between `0` and `100`. The remaining percentage will be sent to the control branch. `100` sends all contacts to variant branches.</summary>
        public double? SamplingRate { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowMutationNodeWithRevision? SendEmailActionWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowMutationNodeWithRevision SendEmailActionWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowMutationNodeWithRevision? SignupTriggerWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowMutationNodeWithRevision SignupTriggerWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowMutationNodeWithRevision? TimerActionWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowMutationNodeWithRevision TimerActionWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TypeName { get; set; }
#nullable restore
#else
        public string TypeName { get; set; }
#endif
        /// <summary>The unit of time for the timer action node. m = minutes, h = hours, d = days.</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit? Unit { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowMutationNodeWithRevision"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowMutationNodeWithRevision? VariantWorkflowMutationNodeWithRevision { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowMutationNodeWithRevision VariantWorkflowMutationNodeWithRevision { get; set; }
#endif
        /// <summary>The current workflow revision token. Pass the latest value as `expectedRevisionId` on the next workflow mutation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowRevisionId { get; set; }
#nullable restore
#else
        public string WorkflowRevisionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowMutationNodeWithRevision"/> and sets the default values.
        /// </summary>
        public WorkflowMutationNodeWithRevision()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowMutationNodeWithRevision"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.WorkflowMutationNodeWithRevision CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("typeName")?.GetStringValue();
            var result = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowMutationNodeWithRevision();
            if("AddToListTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AddToListTriggerWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowMutationNodeWithRevision();
            }
            else if("AudienceFilter".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AudienceFilterWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowMutationNodeWithRevision();
            }
            else if("BlankTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BlankTriggerWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowMutationNodeWithRevision();
            }
            else if("BranchNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BranchWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowMutationNodeWithRevision();
            }
            else if("ContactPropertyTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContactPropertyTriggerWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeWithRevision();
            }
            else if("EventTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EventTriggerWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowMutationNodeWithRevision();
            }
            else if("ExitAction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExitActionWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowMutationNodeWithRevision();
            }
            else if("ExperimentBranchNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExperimentBranchWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowMutationNodeWithRevision();
            }
            else if("SendEmailAction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SendEmailActionWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowMutationNodeWithRevision();
            }
            else if("SignupTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SignupTriggerWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowMutationNodeWithRevision();
            }
            else if("TimerAction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TimerActionWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowMutationNodeWithRevision();
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit>() is global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit unitValue)
            {
                result.Unit = unitValue;
            }
            else if("VariantNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.VariantWorkflowMutationNodeWithRevision = new global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowMutationNodeWithRevision();
            }
            else if(parseNode.GetDoubleValue() is double amountValue)
            {
                result.Amount = amountValue;
            }
            else if(parseNode.GetBoolValue() is bool appliesDownstreamValue)
            {
                result.AppliesDownstream = appliesDownstreamValue;
            }
            else if(parseNode.GetStringValue() is string audienceSegmentIdValue)
            {
                result.AudienceSegmentId = audienceSegmentIdValue;
            }
            else if(parseNode.GetStringValue() is string emailMessageIdValue)
            {
                result.EmailMessageId = emailMessageIdValue;
            }
            else if(parseNode.GetStringValue() is string eventNameValue)
            {
                result.EventName = eventNameValue;
            }
            else if(parseNode.GetStringValue() is string idValue)
            {
                result.Id = idValue;
            }
            else if(parseNode.GetBoolValue() is bool isControlValue)
            {
                result.IsControl = isControlValue;
            }
            else if(parseNode.GetStringValue() is string mailingListIdValue)
            {
                result.MailingListId = mailingListIdValue;
            }
            else if(parseNode.GetBoolValue() is bool reEligibleValue)
            {
                result.ReEligible = reEligibleValue;
            }
            else if(parseNode.GetDoubleValue() is double samplingRateValue)
            {
                result.SamplingRate = samplingRateValue;
            }
            else if(parseNode.GetStringValue() is string subjectValue)
            {
                result.Subject = subjectValue;
            }
            else if(parseNode.GetStringValue() is string typeNameValue)
            {
                result.TypeName = typeNameValue;
            }
            else if(parseNode.GetStringValue() is string workflowRevisionIdValue)
            {
                result.WorkflowRevisionId = workflowRevisionIdValue;
            }
            else if(parseNode.GetCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty>(global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty.CreateFromDiscriminatorValue)?.AsList() is List<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty> eventPropertiesValue)
            {
                result.EventProperties = eventPropertiesValue;
            }
            else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> nextNodeIdsValue)
            {
                result.NextNodeIds = nextNodeIdsValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AddToListTriggerWorkflowMutationNodeWithRevision != null)
            {
                return AddToListTriggerWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(AudienceFilter != null)
            {
                return AudienceFilter.GetFieldDeserializers();
            }
            else if(AudienceFilterWorkflowMutationNodeWithRevision != null)
            {
                return AudienceFilterWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(BlankTriggerWorkflowMutationNodeWithRevision != null)
            {
                return BlankTriggerWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(BranchWorkflowMutationNodeWithRevision != null)
            {
                return BranchWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(ContactPropertyQuery != null)
            {
                return ContactPropertyQuery.GetFieldDeserializers();
            }
            else if(ContactPropertyTriggerWorkflowMutationNodeWithRevision != null)
            {
                return ContactPropertyTriggerWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(EventTriggerWorkflowMutationNodeWithRevision != null)
            {
                return EventTriggerWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(ExitActionWorkflowMutationNodeWithRevision != null)
            {
                return ExitActionWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(ExperimentBranchWorkflowMutationNodeWithRevision != null)
            {
                return ExperimentBranchWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(SendEmailActionWorkflowMutationNodeWithRevision != null)
            {
                return SendEmailActionWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(SignupTriggerWorkflowMutationNodeWithRevision != null)
            {
                return SignupTriggerWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(TimerActionWorkflowMutationNodeWithRevision != null)
            {
                return TimerActionWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            else if(VariantWorkflowMutationNodeWithRevision != null)
            {
                return VariantWorkflowMutationNodeWithRevision.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AddToListTriggerWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowMutationNodeWithRevision>(null, AddToListTriggerWorkflowMutationNodeWithRevision);
            }
            else if(AudienceFilter != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter>(null, AudienceFilter);
            }
            else if(AudienceFilterWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowMutationNodeWithRevision>(null, AudienceFilterWorkflowMutationNodeWithRevision);
            }
            else if(BlankTriggerWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowMutationNodeWithRevision>(null, BlankTriggerWorkflowMutationNodeWithRevision);
            }
            else if(BranchWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowMutationNodeWithRevision>(null, BranchWorkflowMutationNodeWithRevision);
            }
            else if(ContactPropertyQuery != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeContactPropertyQuery>(null, ContactPropertyQuery);
            }
            else if(ContactPropertyTriggerWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowMutationNodeWithRevision>(null, ContactPropertyTriggerWorkflowMutationNodeWithRevision);
            }
            else if(EventTriggerWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowMutationNodeWithRevision>(null, EventTriggerWorkflowMutationNodeWithRevision);
            }
            else if(ExitActionWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowMutationNodeWithRevision>(null, ExitActionWorkflowMutationNodeWithRevision);
            }
            else if(ExperimentBranchWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowMutationNodeWithRevision>(null, ExperimentBranchWorkflowMutationNodeWithRevision);
            }
            else if(SendEmailActionWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowMutationNodeWithRevision>(null, SendEmailActionWorkflowMutationNodeWithRevision);
            }
            else if(SignupTriggerWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowMutationNodeWithRevision>(null, SignupTriggerWorkflowMutationNodeWithRevision);
            }
            else if(TimerActionWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowMutationNodeWithRevision>(null, TimerActionWorkflowMutationNodeWithRevision);
            }
            else if(Unit != null)
            {
                writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit>(null, Unit);
            }
            else if(VariantWorkflowMutationNodeWithRevision != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowMutationNodeWithRevision>(null, VariantWorkflowMutationNodeWithRevision);
            }
            else if(Amount != null)
            {
                writer.WriteDoubleValue(null, Amount);
            }
            else if(AppliesDownstream != null)
            {
                writer.WriteBoolValue(null, AppliesDownstream);
            }
            else if(AudienceSegmentId != null)
            {
                writer.WriteStringValue(null, AudienceSegmentId);
            }
            else if(EmailMessageId != null)
            {
                writer.WriteStringValue(null, EmailMessageId);
            }
            else if(EventName != null)
            {
                writer.WriteStringValue(null, EventName);
            }
            else if(Id != null)
            {
                writer.WriteStringValue(null, Id);
            }
            else if(IsControl != null)
            {
                writer.WriteBoolValue(null, IsControl);
            }
            else if(MailingListId != null)
            {
                writer.WriteStringValue(null, MailingListId);
            }
            else if(ReEligible != null)
            {
                writer.WriteBoolValue(null, ReEligible);
            }
            else if(SamplingRate != null)
            {
                writer.WriteDoubleValue(null, SamplingRate);
            }
            else if(Subject != null)
            {
                writer.WriteStringValue(null, Subject);
            }
            else if(TypeName != null)
            {
                writer.WriteStringValue(null, TypeName);
            }
            else if(WorkflowRevisionId != null)
            {
                writer.WriteStringValue(null, WorkflowRevisionId);
            }
            else if(EventProperties != null)
            {
                writer.WriteCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty>(null, EventProperties);
            }
            else if(NextNodeIds != null)
            {
                writer.WriteCollectionOfPrimitiveValues<string>(null, NextNodeIds);
            }
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
