// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>The comparison operator. It must be valid for the selected contact property&apos;s type and for the `is` or `was` side of the comparison. Number and boolean properties allow `empty` on `was`, but not on `is`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowContactPropertyComparisonOperator
    {
        [EnumMember(Value = "any")]
        #pragma warning disable CS1591
        Any,
        #pragma warning restore CS1591
        [EnumMember(Value = "contains")]
        #pragma warning disable CS1591
        Contains,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_contains")]
        #pragma warning disable CS1591
        NotContains,
        #pragma warning restore CS1591
        [EnumMember(Value = "empty")]
        #pragma warning disable CS1591
        Empty,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_empty")]
        #pragma warning disable CS1591
        NotEmpty,
        #pragma warning restore CS1591
        [EnumMember(Value = "equal")]
        #pragma warning disable CS1591
        Equal,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_equal")]
        #pragma warning disable CS1591
        NotEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "greater_than")]
        #pragma warning disable CS1591
        GreaterThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "less_than")]
        #pragma warning disable CS1591
        LessThan,
        #pragma warning restore CS1591
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "false")]
        #pragma warning disable CS1591
        FalseValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "numeric_equal")]
        #pragma warning disable CS1591
        NumericEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "numeric_not_equal")]
        #pragma warning disable CS1591
        NumericNotEqual,
        #pragma warning restore CS1591
        [EnumMember(Value = "after")]
        #pragma warning disable CS1591
        After,
        #pragma warning restore CS1591
        [EnumMember(Value = "before")]
        #pragma warning disable CS1591
        Before,
        #pragma warning restore CS1591
        [EnumMember(Value = "between")]
        #pragma warning disable CS1591
        Between,
        #pragma warning restore CS1591
    }
}
