// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkflowTimerUnit
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "m")]
        #pragma warning disable CS1591
        M,
        #pragma warning restore CS1591
        [EnumMember(Value = "h")]
        #pragma warning disable CS1591
        H,
        #pragma warning restore CS1591
        [EnumMember(Value = "d")]
        #pragma warning disable CS1591
        D,
        #pragma warning restore CS1591
        [EnumMember(Value = "s")]
        #pragma warning disable CS1591
        S,
        #pragma warning restore CS1591
    }
}
