// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Updates a contact-property trigger, or changes an existing trigger node to a contact-property trigger.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowContactPropertyTriggerPayload : IParsable
    {
        /// <summary>Define the contact property change that triggers the workflow. In update requests, `key` must resolve to an existing contact property that is available for Contact Updated triggers. Hidden or unsupported fields, such as `createdAt`, `notes`, and computed contact properties, are rejected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyQuery? ContactPropertyQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyQuery ContactPropertyQuery { get; set; }
#endif
        /// <summary>If `true`, the contacts will be able to enter this workflow every time the trigger is matched. If `false`, contacts will only ever enter this workflow once. Matches the &quot;Trigger frequency&quot; option in the UI.</summary>
        public bool? ReEligible { get; set; }
        /// <summary>The typeName property</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayloadTypeName? TypeName { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contactPropertyQuery", n => { ContactPropertyQuery = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyQuery>(global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyQuery.CreateFromDiscriminatorValue); } },
                { "reEligible", n => { ReEligible = n.GetBoolValue(); } },
                { "typeName", n => { TypeName = n.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayloadTypeName>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyQuery>("contactPropertyQuery", ContactPropertyQuery);
            writer.WriteBoolValue("reEligible", ReEligible);
            writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowContactPropertyTriggerPayloadTypeName>("typeName", TypeName);
        }
    }
}
#pragma warning restore CS0618
