// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowNode"/>, <see cref="global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowNode"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowNode : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowNode? AddToListTriggerWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowNode AddToListTriggerWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowNode? AudienceFilterWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowNode AudienceFilterWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowNode? BlankTriggerWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowNode BlankTriggerWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowNode? BranchWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowNode BranchWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNode? ContactPropertyTriggerWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNode ContactPropertyTriggerWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowNode? EventTriggerWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowNode EventTriggerWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowNode? ExitActionWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowNode ExitActionWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowNode? ExperimentBranchWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowNode ExperimentBranchWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowNode? SendEmailActionWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowNode SendEmailActionWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowNode? SignupTriggerWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowNode SignupTriggerWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowNode? TimerActionWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowNode TimerActionWorkflowNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowNode? VariantWorkflowNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowNode VariantWorkflowNode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("typeName")?.GetStringValue();
            var result = new global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode();
            if("AddToListTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AddToListTriggerWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowNode();
            }
            else if("AudienceFilter".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AudienceFilterWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowNode();
            }
            else if("BlankTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BlankTriggerWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowNode();
            }
            else if("BranchNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.BranchWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowNode();
            }
            else if("ContactPropertyTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContactPropertyTriggerWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNode();
            }
            else if("EventTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EventTriggerWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowNode();
            }
            else if("ExitAction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExitActionWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowNode();
            }
            else if("ExperimentBranchNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExperimentBranchWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowNode();
            }
            else if("SendEmailAction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SendEmailActionWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowNode();
            }
            else if("SignupTrigger".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SignupTriggerWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowNode();
            }
            else if("TimerAction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TimerActionWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowNode();
            }
            else if("VariantNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.VariantWorkflowNode = new global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowNode();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AddToListTriggerWorkflowNode != null)
            {
                return AddToListTriggerWorkflowNode.GetFieldDeserializers();
            }
            else if(AudienceFilterWorkflowNode != null)
            {
                return AudienceFilterWorkflowNode.GetFieldDeserializers();
            }
            else if(BlankTriggerWorkflowNode != null)
            {
                return BlankTriggerWorkflowNode.GetFieldDeserializers();
            }
            else if(BranchWorkflowNode != null)
            {
                return BranchWorkflowNode.GetFieldDeserializers();
            }
            else if(ContactPropertyTriggerWorkflowNode != null)
            {
                return ContactPropertyTriggerWorkflowNode.GetFieldDeserializers();
            }
            else if(EventTriggerWorkflowNode != null)
            {
                return EventTriggerWorkflowNode.GetFieldDeserializers();
            }
            else if(ExitActionWorkflowNode != null)
            {
                return ExitActionWorkflowNode.GetFieldDeserializers();
            }
            else if(ExperimentBranchWorkflowNode != null)
            {
                return ExperimentBranchWorkflowNode.GetFieldDeserializers();
            }
            else if(SendEmailActionWorkflowNode != null)
            {
                return SendEmailActionWorkflowNode.GetFieldDeserializers();
            }
            else if(SignupTriggerWorkflowNode != null)
            {
                return SignupTriggerWorkflowNode.GetFieldDeserializers();
            }
            else if(TimerActionWorkflowNode != null)
            {
                return TimerActionWorkflowNode.GetFieldDeserializers();
            }
            else if(VariantWorkflowNode != null)
            {
                return VariantWorkflowNode.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AddToListTriggerWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AddToListTriggerWorkflowNode>(null, AddToListTriggerWorkflowNode);
            }
            else if(AudienceFilterWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilterWorkflowNode>(null, AudienceFilterWorkflowNode);
            }
            else if(BlankTriggerWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.BlankTriggerWorkflowNode>(null, BlankTriggerWorkflowNode);
            }
            else if(BranchWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.BranchWorkflowNode>(null, BranchWorkflowNode);
            }
            else if(ContactPropertyTriggerWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNode>(null, ContactPropertyTriggerWorkflowNode);
            }
            else if(EventTriggerWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.EventTriggerWorkflowNode>(null, EventTriggerWorkflowNode);
            }
            else if(ExitActionWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ExitActionWorkflowNode>(null, ExitActionWorkflowNode);
            }
            else if(ExperimentBranchWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ExperimentBranchWorkflowNode>(null, ExperimentBranchWorkflowNode);
            }
            else if(SendEmailActionWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.SendEmailActionWorkflowNode>(null, SendEmailActionWorkflowNode);
            }
            else if(SignupTriggerWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.SignupTriggerWorkflowNode>(null, SignupTriggerWorkflowNode);
            }
            else if(TimerActionWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.TimerActionWorkflowNode>(null, TimerActionWorkflowNode);
            }
            else if(VariantWorkflowNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.VariantWorkflowNode>(null, VariantWorkflowNode);
            }
        }
    }
}
#pragma warning restore CS0618
