// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowNode : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount of time to wait before triggering the next node. Set to `0` to move to the next node immediately.</summary>
        public double? Amount { get; set; }
        /// <summary>If `true`, the audience filter will apply to all downstream nodes. If `false`, the audience filter will only apply to the current node. Matches the &quot;Filter scope&quot; option in the UI.</summary>
        public bool? AppliesDownstream { get; set; }
        /// <summary>A tree of audience conditions combined with `match`. Null when the campaign targets a mailing list or segment without an explicit filter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter? AudienceFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter AudienceFilter { get; set; }
#endif
        /// <summary>The audienceSegmentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AudienceSegmentId { get; set; }
#nullable restore
#else
        public string AudienceSegmentId { get; set; }
#endif
        /// <summary>The contactPropertyQuery property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNodeContactPropertyQuery? ContactPropertyQuery { get; set; }
#nullable restore
#else
        public global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNodeContactPropertyQuery ContactPropertyQuery { get; set; }
#endif
        /// <summary>The ID of the email message to send. To edit this email, use the `POST /v1/email-messages/{emailMessageId}` endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailMessageId { get; set; }
#nullable restore
#else
        public string EmailMessageId { get; set; }
#endif
        /// <summary>The name of the event pattern that triggers this node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventName { get; set; }
#nullable restore
#else
        public string EventName { get; set; }
#endif
        /// <summary>The properties of the event pattern, which can be used in emails.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty>? EventProperties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty> EventProperties { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this is the control variant of an experiment.</summary>
        public bool? IsControl { get; set; }
        /// <summary>The mailingListId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailingListId { get; set; }
#nullable restore
#else
        public string MailingListId { get; set; }
#endif
        /// <summary>The IDs of the nodes that are downstream of this node.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NextNodeIds { get; set; }
#nullable restore
#else
        public List<string> NextNodeIds { get; set; }
#endif
        /// <summary>If `true`, the contacts will be able to enter this workflow every time the trigger is matched. If `false`, contacts will only ever enter this workflow once. Matches the &quot;Trigger frequency&quot; option in the UI.</summary>
        public bool? ReEligible { get; set; }
        /// <summary>The percentage of contacts that will be sent to variant branches, between `0` and `100`. The remaining percentage will be sent to the control branch. `100` sends all contacts to variant branches.</summary>
        public double? SamplingRate { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TypeName { get; set; }
#nullable restore
#else
        public string TypeName { get; set; }
#endif
        /// <summary>The unit of time for the timer action node. m = minutes, h = hours, d = days.</summary>
        public global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit? Unit { get; set; }
        /// <summary>The workflowId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowId { get; set; }
#nullable restore
#else
        public string WorkflowId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode"/> and sets the default values.
        /// </summary>
        public WorkflowNode()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.WorkflowNode();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "appliesDownstream", n => { AppliesDownstream = n.GetBoolValue(); } },
                { "audienceFilter", n => { AudienceFilter = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter>(global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter.CreateFromDiscriminatorValue); } },
                { "audienceSegmentId", n => { AudienceSegmentId = n.GetStringValue(); } },
                { "contactPropertyQuery", n => { ContactPropertyQuery = n.GetObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNodeContactPropertyQuery>(global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNodeContactPropertyQuery.CreateFromDiscriminatorValue); } },
                { "emailMessageId", n => { EmailMessageId = n.GetStringValue(); } },
                { "eventName", n => { EventName = n.GetStringValue(); } },
                { "eventProperties", n => { EventProperties = n.GetCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty>(global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isControl", n => { IsControl = n.GetBoolValue(); } },
                { "mailingListId", n => { MailingListId = n.GetStringValue(); } },
                { "nextNodeIds", n => { NextNodeIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "reEligible", n => { ReEligible = n.GetBoolValue(); } },
                { "samplingRate", n => { SamplingRate = n.GetDoubleValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "typeName", n => { TypeName = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit>(); } },
                { "workflowId", n => { WorkflowId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteBoolValue("appliesDownstream", AppliesDownstream);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.AudienceFilter>("audienceFilter", AudienceFilter);
            writer.WriteStringValue("audienceSegmentId", AudienceSegmentId);
            writer.WriteObjectValue<global::Soenneker.Loops.OpenApiClient.Models.ContactPropertyTriggerWorkflowNodeContactPropertyQuery>("contactPropertyQuery", ContactPropertyQuery);
            writer.WriteStringValue("emailMessageId", EmailMessageId);
            writer.WriteStringValue("eventName", EventName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Loops.OpenApiClient.Models.WorkflowEventProperty>("eventProperties", EventProperties);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isControl", IsControl);
            writer.WriteStringValue("mailingListId", MailingListId);
            writer.WriteCollectionOfPrimitiveValues<string>("nextNodeIds", NextNodeIds);
            writer.WriteBoolValue("reEligible", ReEligible);
            writer.WriteDoubleValue("samplingRate", SamplingRate);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("typeName", TypeName);
            writer.WriteEnumValue<global::Soenneker.Loops.OpenApiClient.Models.WorkflowTimerUnit>("unit", Unit);
            writer.WriteStringValue("workflowId", WorkflowId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
