// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Loops.OpenApiClient.Contacts.Create;
using Soenneker.Loops.OpenApiClient.Contacts.Delete;
using Soenneker.Loops.OpenApiClient.Contacts.Find;
using Soenneker.Loops.OpenApiClient.Contacts.Properties;
using Soenneker.Loops.OpenApiClient.Contacts.Update;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Loops.OpenApiClient.Contacts
{
    /// <summary>
    /// Builds and executes requests for operations under \contacts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContactsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Soenneker.Loops.OpenApiClient.Contacts.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Loops.OpenApiClient.Contacts.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Soenneker.Loops.OpenApiClient.Contacts.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Soenneker.Loops.OpenApiClient.Contacts.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The find property</summary>
        public global::Soenneker.Loops.OpenApiClient.Contacts.Find.FindRequestBuilder Find
        {
            get => new global::Soenneker.Loops.OpenApiClient.Contacts.Find.FindRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The properties property</summary>
        public global::Soenneker.Loops.OpenApiClient.Contacts.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::Soenneker.Loops.OpenApiClient.Contacts.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Soenneker.Loops.OpenApiClient.Contacts.Update.UpdateRequestBuilder Update
        {
            get => new global::Soenneker.Loops.OpenApiClient.Contacts.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Contacts.ContactsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContactsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/contacts", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
