// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Loops.OpenApiClient.V1.Uploads.Item.Complete;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Loops.OpenApiClient.V1.Uploads.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\uploads\{emailAssetId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEmailAssetItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The complete property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Uploads.Item.Complete.CompleteRequestBuilder Complete
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Uploads.Item.Complete.CompleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.Uploads.Item.WithEmailAssetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEmailAssetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/uploads/{emailAssetId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.Uploads.Item.WithEmailAssetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEmailAssetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/uploads/{emailAssetId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
