// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Loops.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListTransactionalsResponse_pagination : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The nextCursor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextCursor { get; set; }
#nullable restore
#else
        public string NextCursor { get; set; }
#endif
        /// <summary>The nextPage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextPage { get; set; }
#nullable restore
#else
        public string NextPage { get; set; }
#endif
        /// <summary>The perPage property</summary>
        public double? PerPage { get; set; }
        /// <summary>The returnedResults property</summary>
        public double? ReturnedResults { get; set; }
        /// <summary>The totalPages property</summary>
        public double? TotalPages { get; set; }
        /// <summary>The totalResults property</summary>
        public double? TotalResults { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.Models.ListTransactionalsResponse_pagination"/> and sets the default values.
        /// </summary>
        public ListTransactionalsResponse_pagination()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.ListTransactionalsResponse_pagination"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Loops.OpenApiClient.Models.ListTransactionalsResponse_pagination CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Loops.OpenApiClient.Models.ListTransactionalsResponse_pagination();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "nextCursor", n => { NextCursor = n.GetStringValue(); } },
                { "nextPage", n => { NextPage = n.GetStringValue(); } },
                { "perPage", n => { PerPage = n.GetDoubleValue(); } },
                { "returnedResults", n => { ReturnedResults = n.GetDoubleValue(); } },
                { "totalPages", n => { TotalPages = n.GetDoubleValue(); } },
                { "totalResults", n => { TotalResults = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("nextCursor", NextCursor);
            writer.WriteStringValue("nextPage", NextPage);
            writer.WriteDoubleValue("perPage", PerPage);
            writer.WriteDoubleValue("returnedResults", ReturnedResults);
            writer.WriteDoubleValue("totalPages", TotalPages);
            writer.WriteDoubleValue("totalResults", TotalResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
