// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Loops.OpenApiClient.ApiKey;
using Soenneker.Loops.OpenApiClient.Contacts;
using Soenneker.Loops.OpenApiClient.DedicatedSendingIps;
using Soenneker.Loops.OpenApiClient.Events;
using Soenneker.Loops.OpenApiClient.Lists;
using Soenneker.Loops.OpenApiClient.Transactional;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Loops.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoopsOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The apiKey property</summary>
        public global::Soenneker.Loops.OpenApiClient.ApiKey.ApiKeyRequestBuilder ApiKey
        {
            get => new global::Soenneker.Loops.OpenApiClient.ApiKey.ApiKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Soenneker.Loops.OpenApiClient.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Soenneker.Loops.OpenApiClient.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dedicatedSendingIps property</summary>
        public global::Soenneker.Loops.OpenApiClient.DedicatedSendingIps.DedicatedSendingIpsRequestBuilder DedicatedSendingIps
        {
            get => new global::Soenneker.Loops.OpenApiClient.DedicatedSendingIps.DedicatedSendingIpsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Soenneker.Loops.OpenApiClient.Events.EventsRequestBuilder Events
        {
            get => new global::Soenneker.Loops.OpenApiClient.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::Soenneker.Loops.OpenApiClient.Lists.ListsRequestBuilder Lists
        {
            get => new global::Soenneker.Loops.OpenApiClient.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactional property</summary>
        public global::Soenneker.Loops.OpenApiClient.Transactional.TransactionalRequestBuilder Transactional
        {
            get => new global::Soenneker.Loops.OpenApiClient.Transactional.TransactionalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.LoopsOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoopsOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://app.loops.so/api/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
