// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Loops.OpenApiClient.Models;
using Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.AddBranch;
using Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.Recursive;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workflows\{workflowId}\nodes\{nodeId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithNodeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addBranch property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.AddBranch.AddBranchRequestBuilder AddBranch
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.AddBranch.AddBranchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recursive property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.Recursive.RecursiveRequestBuilder Recursive
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.Recursive.RecursiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.WithNodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNodeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workflows/{workflowId}/nodes/{nodeId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.WithNodeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNodeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workflows/{workflowId}/nodes/{nodeId}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Delete a single workflow node. If contacts are queued at the node, Loops returns with `\&quot;status\&quot;: \&quot;queuedContactsFound\&quot;` instead of deleting. Retry with `queuedContactPolicy: \&quot;discard\&quot;` to delete the node and discard those queued contacts.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeResponse?> DeleteAsync(global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeResponse> DeleteAsync(global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeResponse>(requestInfo, global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve detailed data for a single workflow node.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowNodeWithRevision"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.WorkflowNodeWithRevision?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.WorkflowNodeWithRevision> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Loops.OpenApiClient.Models.WorkflowNodeWithRevision>(requestInfo, global::Soenneker.Loops.OpenApiClient.Models.WorkflowNodeWithRevision.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update workflow-node-owned fields for a single node. Shared resources such as email messages and audience segments should be updated through their own APIs.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 501 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeResponse?> PostAsync(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeResponse> PostAsync(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "501", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeResponse>(requestInfo, global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Delete a single workflow node. If contacts are queued at the node, Loops returns with `\&quot;status\&quot;: \&quot;queuedContactsFound\&quot;` instead of deleting. Retry with `queuedContactPolicy: \&quot;discard\&quot;` to delete the node and discard those queued contacts.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::Soenneker.Loops.OpenApiClient.Models.DeleteWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Retrieve detailed data for a single workflow node.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update workflow-node-owned fields for a single node. Shared resources such as email messages and audience segments should be updated through their own APIs.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowNodeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.WithNodeItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.WithNodeItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.Item.WithNodeItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
