// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Loops.OpenApiClient.Models;
using Soenneker.Loops.OpenApiClient.V1.Workflows.Item.MailingList;
using Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Loops.OpenApiClient.V1.Workflows.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\workflows\{workflowId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithWorkflowItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mailingList property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.MailingList.MailingListRequestBuilder MailingList
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.MailingList.MailingListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The nodes property</summary>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.NodesRequestBuilder Nodes
        {
            get => new global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.Nodes.NodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.WithWorkflowItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkflowItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workflows/{workflowId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.WithWorkflowItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkflowItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/workflows/{workflowId}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve a workflow graph with node type names, connections, and selected display fields.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow>(requestInfo, global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a workflow&apos;s display properties. At least one property must be provided. To change the workflow&apos;s mailing list, use the `/v1/workflows/{workflowId}/mailing-list` endpoint instead.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow"/></returns>
        /// <param name="body">At least one property must be provided.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse">When receiving a 409 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow?> PostAsync(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowPropertiesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow> PostAsync(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowPropertiesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Loops.OpenApiClient.Models.WorkflowFailureResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow>(requestInfo, global::Soenneker.Loops.OpenApiClient.Models.SimplifiedWorkflow.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a workflow graph with node type names, connections, and selected display fields.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a workflow&apos;s display properties. At least one property must be provided. To change the workflow&apos;s mailing list, use the `/v1/workflows/{workflowId}/mailing-list` endpoint instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">At least one property must be provided.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowPropertiesRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Loops.OpenApiClient.Models.UpdateWorkflowPropertiesRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.WithWorkflowItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.WithWorkflowItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Loops.OpenApiClient.V1.Workflows.Item.WithWorkflowItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
